name: Run Python Job

on:
  schedule:
    # roda toda sexta às 12:00 UTC (09:00 no Brasil, UTC-3)
    - cron: "0 12 * * THU"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create .env file
        run: |
          echo "${{ secrets.DOTENV_FILE }}" > .env

      - name: Run script
        run: python main.py
